// Auto-generated by Myra  Attribute Set Wizard.
// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.
// Copyright Your Project. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "AbilitySystem/MyraAttributeSet.h"
#include "MyraRPGSetAttributeSet.generated.h"

#ifndef ATTRIBUTE_ACCESSORS
#define ATTRIBUTE_ACCESSORS(ClassName, PropertyName) \
	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(ClassName, PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_GETTER(PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_SETTER(PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)
#endif

UCLASS()
class MYRA_API UMyraRPGSetAttributeSet : public UMyraAttributeSet
{
	GENERATED_BODY()

public:

	UMyraRPGSetAttributeSet();

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
	virtual void PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue) override;
	virtual void PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data) override;

	/** Mana Attribute */
	UPROPERTY(BlueprintReadOnly, Category = "RPGSet", ReplicatedUsing = OnRep_Mana)
	FGameplayAttributeData Mana;
	ATTRIBUTE_ACCESSORS(UMyraRPGSetAttributeSet, Mana)

	/** Maximum value for Mana. */
	UPROPERTY(BlueprintReadOnly, Category = "RPGSet", ReplicatedUsing = OnRep_MaxMana)
	FGameplayAttributeData MaxMana;
	ATTRIBUTE_ACCESSORS(UMyraRPGSetAttributeSet, MaxMana)

	/** Stamina Attribute */
	UPROPERTY(BlueprintReadOnly, Category = "RPGSet", ReplicatedUsing = OnRep_Stamina)
	FGameplayAttributeData Stamina;
	ATTRIBUTE_ACCESSORS(UMyraRPGSetAttributeSet, Stamina)

	/** Maximum value for Stamina. */
	UPROPERTY(BlueprintReadOnly, Category = "RPGSet", ReplicatedUsing = OnRep_MaxStamina)
	FGameplayAttributeData MaxStamina;
	ATTRIBUTE_ACCESSORS(UMyraRPGSetAttributeSet, MaxStamina)

protected:

	UFUNCTION()
	virtual void OnRep_Mana(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxMana(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Stamina(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxStamina(const FGameplayAttributeData& OldValue);

};
