// Auto-generated by Myra  Attribute Set Wizard.
// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.
// Copyright Your Project. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "AbilitySystem/MyraAttributeSet.h"
#include "MyraCombatAttributeSet.generated.h"

#ifndef ATTRIBUTE_ACCESSORS
#define ATTRIBUTE_ACCESSORS(ClassName, PropertyName) \
	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(ClassName, PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_GETTER(PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_SETTER(PropertyName) \
	GAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)
#endif

UCLASS()
class MYRA_API UMyraCombatAttributeSet : public UMyraAttributeSet
{
	GENERATED_BODY()

public:

	UMyraCombatAttributeSet();

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
	virtual void PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue) override;
	virtual void PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data) override;

	/** The Vitality attribute. */
	UPROPERTY(BlueprintReadOnly, Category = "Combat", ReplicatedUsing = OnRep_Vitality)
	FGameplayAttributeData Vitality;
	ATTRIBUTE_ACCESSORS(UMyraCombatAttributeSet, Vitality)

	/** Maximum value for Vitality. */
	UPROPERTY(BlueprintReadOnly, Category = "Combat", ReplicatedUsing = OnRep_MaxVitality)
	FGameplayAttributeData MaxVitality;
	ATTRIBUTE_ACCESSORS(UMyraCombatAttributeSet, MaxVitality)

	/** The Endurance attribute. */
	UPROPERTY(BlueprintReadOnly, Category = "Combat", ReplicatedUsing = OnRep_Endurance)
	FGameplayAttributeData Endurance;
	ATTRIBUTE_ACCESSORS(UMyraCombatAttributeSet, Endurance)

	/** Maximum value for Endurance. */
	UPROPERTY(BlueprintReadOnly, Category = "Combat", ReplicatedUsing = OnRep_MaxEndurance)
	FGameplayAttributeData MaxEndurance;
	ATTRIBUTE_ACCESSORS(UMyraCombatAttributeSet, MaxEndurance)

	/** The AttackPower attribute. */
	UPROPERTY(BlueprintReadOnly, Category = "Combat", ReplicatedUsing = OnRep_AttackPower)
	FGameplayAttributeData AttackPower;
	ATTRIBUTE_ACCESSORS(UMyraCombatAttributeSet, AttackPower)

protected:

	UFUNCTION()
	virtual void OnRep_Vitality(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxVitality(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Endurance(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxEndurance(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_AttackPower(const FGameplayAttributeData& OldValue);

};
