// Copyright Myra . All Rights Reserved.

#include "MyraAttributeSetGenerator.h"
#include "DataAssets/MyraAttributeDefinition.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Interfaces/IPluginManager.h"

// ============================================================
//  Public entry point
// ============================================================

FMyraGenerationResult FMyraAttributeSetGenerator::GenerateAttributeSet(
	const UMyraAttributeDefinition* Definition,
	bool bOverwrite)
{
	FMyraGenerationResult Result;
	FString PublicOutputDirectory;
	FString PrivateOutputDirectory;

	if (!ValidateDefinition(Definition, Result))
	{
		return Result; // Errors already added
	}

	if (!ResolveOutputDirectories(PublicOutputDirectory, PrivateOutputDirectory, Result))
	{
		return Result;
	}

	// Class name: e.g. "Combat" → "UMyraCombatAttributeSet"
	const FString ClassName = FString::Printf(TEXT("Myra%sAttributeSet"), *Definition->AttributeSetName.ToString());
	const FString HeaderName = ClassName + TEXT(".h");
	const FString SourceName = ClassName + TEXT(".cpp");
	const FString HeaderPath = FPaths::Combine(PublicOutputDirectory, HeaderName);
	const FString SourcePath = FPaths::Combine(PrivateOutputDirectory, SourceName);
	const FString HeaderIncludePath = FString::Printf(
		TEXT("AbilitySystem/CustomAttributeSets/%s"),
		*HeaderName);

	// Build file contents
	const FString HeaderContent = BuildHeaderContent(Definition, ClassName);
	const FString SourceContent = BuildSourceContent(Definition, ClassName, HeaderIncludePath);

	// Write both files
	if (!WriteFile(HeaderPath, HeaderContent, bOverwrite, Result)) return Result;
	if (!WriteFile(SourcePath, SourceContent, bOverwrite, Result)) return Result;

	Result.bSuccess            = true;
	Result.GeneratedHeaderPath = HeaderPath;
	Result.GeneratedSourcePath = SourcePath;
	Result.AddMessage(FString::Printf(
		TEXT("Successfully generated:\n  %s\n  %s"), *HeaderPath, *SourcePath));

	return Result;
}

// ============================================================
//  Header generation
// ============================================================

FString FMyraAttributeSetGenerator::BuildHeaderContent(
	const UMyraAttributeDefinition* Definition, const FString& ClassName)
{
	const FString SetName = Definition->AttributeSetName.ToString();
	FString Out;

	Out += TEXT("// Auto-generated by Myra  Attribute Set Wizard.\n");
	Out += TEXT("// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.\n");
	Out += TEXT("// Copyright Your Project. All Rights Reserved.\n");
	Out += TEXT("#pragma once\n\n");
	Out += TEXT("#include \"CoreMinimal.h\"\n");
	Out += TEXT("#include \"AbilitySystem/MyraAttributeSet.h\"\n");

	for (const FString& Extra : Definition->ExtraIncludes)
	{
		Out += FString::Printf(TEXT("#include \"%s\"\n"), *Extra);
	}

	Out += FString::Printf(TEXT("#include \"%s.generated.h\"\n\n"), *ClassName);

	Out += TEXT("#ifndef ATTRIBUTE_ACCESSORS\n");
	Out += TEXT("#define ATTRIBUTE_ACCESSORS(ClassName, PropertyName) \\\n");
	Out += TEXT("\tGAMEPLAYATTRIBUTE_PROPERTY_GETTER(ClassName, PropertyName) \\\n");
	Out += TEXT("\tGAMEPLAYATTRIBUTE_VALUE_GETTER(PropertyName) \\\n");
	Out += TEXT("\tGAMEPLAYATTRIBUTE_VALUE_SETTER(PropertyName) \\\n");
	Out += TEXT("\tGAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)\n");
	Out += TEXT("#endif\n\n");

	Out += FString::Printf(TEXT("UCLASS()\nclass MYRA_API U%s : public UMyraAttributeSet\n{\n\tGENERATED_BODY()\n\npublic:\n\n"),
		*ClassName);

	Out += FString::Printf(TEXT("\tU%s();\n\n"), *ClassName);
	Out += TEXT("\tvirtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;\n");
	Out += TEXT("\tvirtual void PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue) override;\n");
	Out += TEXT("\tvirtual void PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data) override;\n\n");

	// Declare each attribute
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (!Entry.AttributeName.IsValid() || Entry.AttributeName.IsNone()) continue;

		const FString AttrName = Entry.AttributeName.ToString();
		const bool bMeta = Entry.bIsMetaAttribute;
		const bool bRep  = Entry.bReplicated && !bMeta;

		Out += FString::Printf(TEXT("\t/** %s */\n"), Entry.Tooltip.IsEmpty()
			? *FString::Printf(TEXT("The %s attribute."), *AttrName)
			: *Entry.Tooltip.ToString());

		if (bRep)
			Out += FString::Printf(TEXT("\tUPROPERTY(BlueprintReadOnly, Category = \"%s\", ReplicatedUsing = OnRep_%s)\n"), *SetName, *AttrName);
		else
			Out += TEXT("\tUPROPERTY(BlueprintReadOnly)\n");

		Out += FString::Printf(TEXT("\tFGameplayAttributeData %s;\n"), *AttrName);
		Out += FString::Printf(TEXT("\tATTRIBUTE_ACCESSORS(U%s, %s)\n\n"), *ClassName, *AttrName);

		// MaxAttribute
		if (Entry.bCreateMaxAttribute && !bMeta)
		{
			const FString MaxName = TEXT("Max") + AttrName;
			Out += FString::Printf(TEXT("\t/** Maximum value for %s. */\n"), *AttrName);
			Out += FString::Printf(TEXT("\tUPROPERTY(BlueprintReadOnly, Category = \"%s\", ReplicatedUsing = OnRep_%s)\n"), *SetName, *MaxName);
			Out += FString::Printf(TEXT("\tFGameplayAttributeData %s;\n"), *MaxName);
			Out += FString::Printf(TEXT("\tATTRIBUTE_ACCESSORS(U%s, %s)\n\n"), *ClassName, *MaxName);
		}
	}

	Out += TEXT("protected:\n\n");

	// OnRep declarations (only for replicated, non-meta attributes)
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (Entry.bIsMetaAttribute || !Entry.bReplicated) continue;
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("\tUFUNCTION()\n\tvirtual void OnRep_%s(const FGameplayAttributeData& OldValue);\n\n"), *AttrName);
		if (Entry.bCreateMaxAttribute)
		{
			Out += FString::Printf(TEXT("\tUFUNCTION()\n\tvirtual void OnRep_Max%s(const FGameplayAttributeData& OldValue);\n\n"), *AttrName);
		}
	}

	Out += TEXT("};\n");
	return Out;
}

// ============================================================
//  Source generation
// ============================================================

FString FMyraAttributeSetGenerator::BuildSourceContent(
	const UMyraAttributeDefinition* Definition,
	const FString& ClassName,
	const FString& HeaderRelPath)
{
	FString Out;

	Out += TEXT("// Auto-generated by Myra  Attribute Set Wizard.\n");
	Out += TEXT("// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.\n\n");
	Out += FString::Printf(TEXT("#include \"%s\"\n"), *HeaderRelPath);
	Out += TEXT("#include \"GameplayEffectExtension.h\"\n");
	Out += TEXT("#include \"Net/UnrealNetwork.h\"\n");
	Out += TEXT("#include \"AbilitySystemComponent.h\"\n\n");

	// Constructor
	Out += FString::Printf(TEXT("U%s::U%s()\n{\n"), *ClassName, *ClassName);
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (!Entry.AttributeName.IsValid()) continue;
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("\tInit%s(%.1ff);\n"), *AttrName, Entry.DefaultValue);
		if (Entry.bCreateMaxAttribute && !Entry.bIsMetaAttribute)
		{
			Out += FString::Printf(TEXT("\tInitMax%s(%.1ff);\n"), *AttrName, Entry.MaxDefaultValue);
		}
	}
	Out += TEXT("}\n\n");

	// GetLifetimeReplicatedProps
	Out += FString::Printf(TEXT("void U%s::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const\n{\n"), *ClassName);
	Out += TEXT("\tSuper::GetLifetimeReplicatedProps(OutLifetimeProps);\n\n");
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (Entry.bIsMetaAttribute || !Entry.bReplicated) continue;
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("\tDOREPLIFETIME_CONDITION_NOTIFY(U%s, %s, COND_None, REPNOTIFY_Always);\n"), *ClassName, *AttrName);
		if (Entry.bCreateMaxAttribute)
			Out += FString::Printf(TEXT("\tDOREPLIFETIME_CONDITION_NOTIFY(U%s, Max%s, COND_None, REPNOTIFY_Always);\n"), *ClassName, *AttrName);
	}
	Out += TEXT("}\n\n");

	// PreAttributeChange
	Out += FString::Printf(TEXT("void U%s::PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue)\n{\n"), *ClassName);
	Out += TEXT("\tSuper::PreAttributeChange(Attribute, NewValue);\n\n");
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (Entry.bIsMetaAttribute || !Entry.bCreateMaxAttribute) continue;
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("\tif (Attribute == Get%sAttribute())\n\t\tNewValue = FMath::Clamp(NewValue, 0.f, Get%s());\n"), *AttrName, *(TEXT("Max") + AttrName));
		Out += FString::Printf(TEXT("\telse if (Attribute == GetMax%sAttribute())\n\t\tNewValue = FMath::Max(NewValue, 1.f);\n\n"), *AttrName);
	}
	Out += TEXT("}\n\n");

	// PostGameplayEffectExecute
	Out += FString::Printf(TEXT("void U%s::PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data)\n{\n"), *ClassName);
	Out += TEXT("\tSuper::PostGameplayEffectExecute(Data);\n\n");
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (!Entry.bIsMetaAttribute) continue;
		// Meta attribute handling skeleton
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("\tif (Data.EvaluatedData.Attribute == Get%sAttribute())\n\t{\n"), *AttrName);
		Out += FString::Printf(TEXT("\t\tconst float Local%s = Get%s();\n\t\tSet%s(0.f);\n"), *AttrName, *AttrName, *AttrName);
		Out += TEXT("\t\t// TODO: Apply this value to your target attribute here.\n\t}\n\n");
	}
	Out += TEXT("}\n\n");

	// OnRep implementations
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		if (Entry.bIsMetaAttribute || !Entry.bReplicated) continue;
		const FString AttrName = Entry.AttributeName.ToString();
		Out += FString::Printf(TEXT("void U%s::OnRep_%s(const FGameplayAttributeData& OldValue)\n{\n\tGAMEPLAYATTRIBUTE_REPNOTIFY(U%s, %s, OldValue);\n}\n\n"),
			*ClassName, *AttrName, *ClassName, *AttrName);
		if (Entry.bCreateMaxAttribute)
		{
			Out += FString::Printf(TEXT("void U%s::OnRep_Max%s(const FGameplayAttributeData& OldValue)\n{\n\tGAMEPLAYATTRIBUTE_REPNOTIFY(U%s, Max%s, OldValue);\n}\n\n"),
				*ClassName, *AttrName, *ClassName, *AttrName);
		}
	}

	return Out;
}

// ============================================================
//  File writing
// ============================================================

bool FMyraAttributeSetGenerator::WriteFile(
	const FString& FilePath, const FString& Content,
	bool bOverwrite, FMyraGenerationResult& Result)
{
	if (FPaths::FileExists(FilePath) && !bOverwrite)
	{
		Result.AddError(FString::Printf(
			TEXT("File already exists and bOverwrite is false: %s"), *FilePath));
		return false;
	}

	// Create output directory if needed
	IFileManager::Get().MakeDirectory(*FPaths::GetPath(FilePath), /*Tree=*/true);

	if (!FFileHelper::SaveStringToFile(Content, *FilePath))
	{
		Result.AddError(FString::Printf(TEXT("Failed to write file: %s"), *FilePath));
		return false;
	}

	Result.AddMessage(FString::Printf(TEXT("Wrote: %s"), *FilePath));
	return true;
}

bool FMyraAttributeSetGenerator::ResolveOutputDirectories(
	FString& PublicOutputDirectory,
	FString& PrivateOutputDirectory,
	FMyraGenerationResult& Result)
{
	const TSharedPtr<IPlugin> MyraPlugin = IPluginManager::Get().FindPlugin(TEXT("Myra"));
	if (!MyraPlugin.IsValid())
	{
		Result.AddError(TEXT("Could not locate the Myra plugin."));
		return false;
	}

	const FString ModuleSourceDirectory = FPaths::Combine(MyraPlugin->GetBaseDir(), TEXT("Source"), TEXT("Myra"));
	const FString ModuleBuildFile = FPaths::Combine(ModuleSourceDirectory, TEXT("Myra.Build.cs"));
	if (!FPaths::FileExists(ModuleBuildFile))
	{
		Result.AddError(FString::Printf(
			TEXT("Could not find the Myra module build file: %s"),
			*ModuleBuildFile));
		return false;
	}

	PublicOutputDirectory = FPaths::Combine(ModuleSourceDirectory, TEXT("Public"), TEXT("AbilitySystem"), TEXT("CustomAttributeSets"));
	PrivateOutputDirectory = FPaths::Combine(ModuleSourceDirectory, TEXT("Private"), TEXT("AbilitySystem"), TEXT("CustomAttributeSets"));
	PublicOutputDirectory = FPaths::ConvertRelativePathToFull(PublicOutputDirectory);
	PrivateOutputDirectory = FPaths::ConvertRelativePathToFull(PrivateOutputDirectory);
	FPaths::NormalizeDirectoryName(PublicOutputDirectory);
	FPaths::NormalizeDirectoryName(PrivateOutputDirectory);

	return true;
}

// ============================================================
//  Validation
// ============================================================

bool FMyraAttributeSetGenerator::ValidateDefinition(
	const UMyraAttributeDefinition* Definition, FMyraGenerationResult& Result)
{
	if (!Definition)
	{
		Result.AddError(TEXT("Definition asset is null."));
		return false;
	}

	const FString NameStr = Definition->AttributeSetName.ToString();
	if (NameStr.IsEmpty())
	{
		Result.AddError(TEXT("AttributeSetName is empty."));
		return false;
	}

	if (!FChar::IsAlpha(NameStr[0]))
	{
		Result.AddError(FString::Printf(
			TEXT("AttributeSetName '%s' must start with a letter."), *NameStr));
		return false;
	}

	if (Definition->Attributes.IsEmpty())
	{
		Result.AddError(TEXT("Attributes array is empty — nothing to generate."));
		return false;
	}

	TSet<FName> Seen;
	for (const FMyraAttributeDefinitionEntry& Entry : Definition->Attributes)
	{
		const FString AttrName = Entry.AttributeName.ToString();
		if (AttrName.IsEmpty() || !FChar::IsAlpha(AttrName[0]))
		{
			Result.AddError(FString::Printf(
				TEXT("Invalid attribute name '%s'."), *AttrName));
			return false;
		}
		if (Seen.Contains(Entry.AttributeName))
		{
			Result.AddError(FString::Printf(
				TEXT("Duplicate attribute name '%s'."), *AttrName));
			return false;
		}
		Seen.Add(Entry.AttributeName);
	}

	return true;
}
