// Auto-generated by Myra  Attribute Set Wizard.
// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.

//#include "../../../Engine/Binaries/Win64/AbilitySystem/CustomAttributeSets/MyraCombatAttributeSet.h"
#include "AbilitySystem/CustomAttributeSets/MyraCombatAttributeSet.h"
#include "GameplayEffectExtension.h"
#include "Net/UnrealNetwork.h"
#include "AbilitySystemComponent.h"

UMyraCombatAttributeSet::UMyraCombatAttributeSet()
{
	InitVitality(100.0f);
	InitMaxVitality(100.0f);
	InitEndurance(150.0f);
	InitMaxEndurance(150.0f);
	InitAttackPower(10.0f);
}

void UMyraCombatAttributeSet::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME_CONDITION_NOTIFY(UMyraCombatAttributeSet, Vitality, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraCombatAttributeSet, MaxVitality, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraCombatAttributeSet, Endurance, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraCombatAttributeSet, MaxEndurance, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraCombatAttributeSet, AttackPower, COND_None, REPNOTIFY_Always);
}

void UMyraCombatAttributeSet::PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue)
{
	Super::PreAttributeChange(Attribute, NewValue);

	if (Attribute == GetVitalityAttribute())
		NewValue = FMath::Clamp(NewValue, 0.f, GetMaxVitality());
	else if (Attribute == GetMaxVitalityAttribute())
		NewValue = FMath::Max(NewValue, 1.f);

	if (Attribute == GetEnduranceAttribute())
		NewValue = FMath::Clamp(NewValue, 0.f, GetMaxEndurance());
	else if (Attribute == GetMaxEnduranceAttribute())
		NewValue = FMath::Max(NewValue, 1.f);

}

void UMyraCombatAttributeSet::PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data)
{
	Super::PostGameplayEffectExecute(Data);

}

void UMyraCombatAttributeSet::OnRep_Vitality(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraCombatAttributeSet, Vitality, OldValue);
}

void UMyraCombatAttributeSet::OnRep_MaxVitality(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraCombatAttributeSet, MaxVitality, OldValue);
}

void UMyraCombatAttributeSet::OnRep_Endurance(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraCombatAttributeSet, Endurance, OldValue);
}

void UMyraCombatAttributeSet::OnRep_MaxEndurance(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraCombatAttributeSet, MaxEndurance, OldValue);
}

void UMyraCombatAttributeSet::OnRep_AttackPower(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraCombatAttributeSet, AttackPower, OldValue);
}

