// Auto-generated by Myra  Attribute Set Wizard.
// DO NOT EDIT THIS FILE MANUALLY - re-run the wizard to regenerate.

#include "AbilitySystem/CustomAttributeSets/MyraRPGSetAttributeSet.h"
#include "GameplayEffectExtension.h"
#include "Net/UnrealNetwork.h"
#include "AbilitySystemComponent.h"

UMyraRPGSetAttributeSet::UMyraRPGSetAttributeSet()
{
	InitMana(200.0f);
	InitMaxMana(200.0f);
	InitStamina(100.0f);
	InitMaxStamina(100.0f);
}

void UMyraRPGSetAttributeSet::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME_CONDITION_NOTIFY(UMyraRPGSetAttributeSet, Mana, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraRPGSetAttributeSet, MaxMana, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraRPGSetAttributeSet, Stamina, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UMyraRPGSetAttributeSet, MaxStamina, COND_None, REPNOTIFY_Always);
}

void UMyraRPGSetAttributeSet::PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue)
{
	Super::PreAttributeChange(Attribute, NewValue);

	if (Attribute == GetManaAttribute())
		NewValue = FMath::Clamp(NewValue, 0.f, GetMaxMana());
	else if (Attribute == GetMaxManaAttribute())
		NewValue = FMath::Max(NewValue, 1.f);

	if (Attribute == GetStaminaAttribute())
		NewValue = FMath::Clamp(NewValue, 0.f, GetMaxStamina());
	else if (Attribute == GetMaxStaminaAttribute())
		NewValue = FMath::Max(NewValue, 1.f);

}

void UMyraRPGSetAttributeSet::PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data)
{
	Super::PostGameplayEffectExecute(Data);

}

void UMyraRPGSetAttributeSet::OnRep_Mana(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraRPGSetAttributeSet, Mana, OldValue);
}

void UMyraRPGSetAttributeSet::OnRep_MaxMana(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraRPGSetAttributeSet, MaxMana, OldValue);
}

void UMyraRPGSetAttributeSet::OnRep_Stamina(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraRPGSetAttributeSet, Stamina, OldValue);
}

void UMyraRPGSetAttributeSet::OnRep_MaxStamina(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UMyraRPGSetAttributeSet, MaxStamina, OldValue);
}

